import QuadraticEquation
QuadraticEquation.czytajWspolczynniki()
QuadraticEquation.obliczDelte(QuadraticEquation.wspolczynniki)
QuadraticEquation.obliczPierwiastki(QuadraticEquation.wspolczynniki)
QuadraticEquation.wyswietlPierwiastki(QuadraticEquation.pierwiastki)